application: earthquakehtml5
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /(.*\.(gif|png|jpg|ico|js|css|json))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|json))

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt 

- url: .*
  script: main.py

libraries:
- name: webapp2
  version: "2.5.2"
